apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-demoapp
  labels:
    app: python-demoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-demoapp
  template:
    metadata:
      labels:
        app: python-demoapp
    spec:
      containers:
        - name: python-demoapp
          image: 023703779855.dkr.ecr.ap-south-1.amazonaws.com/development/namespace:14
          ports:
            - containerPort: 8080
