apiVersion: v1
kind: Service
metadata:
  name: python-demoapp-service
spec:
  type: LoadBalancer
  selector:
    app: python-demoapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
